APP_NAME = "YouLoad"
APP_TAGLINE = "by NISPAX InfoTech"
APP_VERSION = "1.0.1"

WORDMARK_FONT = "Jokerman"
UI_FONT = "Segoe UI"

ACCENT_COLOR = "#20C86B"
BACKGROUND_COLOR = "#111315"
PANEL_COLOR = "#181B1D"
TEXT_COLOR = "#F2F5F3"
MUTED_COLOR = "#94999D"

GITHUB_OWNER = "Nispax-Official"
GITHUB_REPOSITORY = "YouLoad"
